import { StyleSheet } from 'react-native';

export const colors = {
  background: '#f6f8f7',
  card: '#ffffff',
  border: '#dce6e3',
  text: '#13201e',
  muted: '#52625f',
  primary: '#0f766e',
  primaryDark: '#0b5f59',
  warningText: '#7c4a00',
  warningBg: '#fff4dc',
  dangerText: '#8a1f11',
  dangerBg: '#fde8e4',
};

export const commonStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 40,
  },
  eyebrow: {
    color: '#a15c00',
    fontSize: 12,
    fontWeight: '900',
    marginTop: 18,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: colors.text,
    fontSize: 48,
    fontWeight: '900',
    lineHeight: 54,
  },
  title: {
    color: colors.text,
    fontSize: 34,
    fontWeight: '900',
    lineHeight: 40,
  },
  lead: {
    color: colors.muted,
    fontSize: 17,
    lineHeight: 27,
    marginTop: 16,
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: 1,
    marginTop: 28,
    padding: 18,
    shadowColor: '#243a35',
    shadowOpacity: 0.09,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 12 },
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    borderRadius: 8,
    borderWidth: 1,
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
    minHeight: 50,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 14,
    textAlign: 'center',
  },
  secondaryButton: {
    backgroundColor: '#ffffff',
    borderColor: colors.primary,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.primary,
    fontSize: 16,
    fontWeight: '900',
    minHeight: 50,
    overflow: 'hidden',
    paddingHorizontal: 18,
    paddingVertical: 14,
    textAlign: 'center',
  },
  iconBox: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  iconText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '900',
  },
  mutedText: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
  },
  errorBox: {
    backgroundColor: colors.dangerBg,
    borderRadius: 8,
    color: colors.dangerText,
    fontSize: 14,
    fontWeight: '800',
    overflow: 'hidden',
    padding: 12,
  },
  successBox: {
    backgroundColor: '#dff6e8',
    borderRadius: 8,
    color: '#115e36',
    fontSize: 14,
    fontWeight: '800',
    overflow: 'hidden',
    padding: 12,
  },
});

